### ISSUE TITLE
there's no image.ub file in prebuild,can you upload one ,thank U

### ISSUE THREAD

**Issue by NarcissusYe** [xelalin/Ultra96v2-DPU#1]
hello, i'm learning DPU,and i have a Ultra96v2,i have tried to generate image.ub and boot.bin but failed.So can you upload a image.ub?Thank you very much!

**Comment by xelalin** [comment]
since the image.ub is over limitation of 100MB. I have compressed and updated it. if you want use it, please use below command to uncompress it
"tar -xzvf image.ub.tar.gz"
