### ISSUE TITLE
Sorry to bother you again.I encountered some problems

### ISSUE THREAD

**Issue by NarcissusYe** [xelalin/Ultra96v2-DPU#2]
I‘m trying to pre-built sdk,because  I need sysroot to build a new SDK app.I tried many times  to build SDK but failed.So  can you upload the sysroot for me .I just flow your steps . 
but I need the sysroots
${workspace_loc}/../petalinux/images/linux/sdk/sysroots/aarch64-xilinx-linux
I would really appreciate your help！
 Best wishes
      Narcissus

**Comment by xelalin** [comment]
The files are too large, so I can not load it to Github. Please use the BSP to regenerate it. 

There are two BSP for your reference.

https://avtinc-my.sharepoint.com/personal/alex_lin_avnet_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Falex%5Flin%5Favnet%5Fcom%2FDocuments%2FDocuments%2FUltra96%5Fv2%5FDPUv3&originalPath=aHR0cHM6Ly9hdnRpbmMtbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvYWxleF9saW5fYXZuZXRfY29tL0VzNjFpcFptVXc1SGhEVXViWi03bDEwQkUtZjJLWkZyNFdHd0JDTnJpQXFKU2c_cnRpbWU9bk5Wam1UeDMxMGc

https://avtinc-my.sharepoint.com/personal/alex_lin_avnet_com/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly9hdnRpbmMtbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvYWxleF9saW5fYXZuZXRfY29tL0VzNjFpcFptVXc1SGhEVXViWi03bDEwQkUtZjJLWkZyNFdHd0JDTnJpQXFKU2c%5FcnRpbWU9bk5Wam1UeDMxMGc&viewid=eb0607a2%2D15ad%2D4219%2Dbd1a%2D041f228f9438&id=%2Fpersonal%2Falex%5Flin%5Favnet%5Fcom%2FDocuments%2FDocuments%2FUltra96%5Fv2%5FDPUv3
